export default

[
   {
      "block":"ADR - DEV MARKETS ABC USD",
      "benchmark":"benchmark 1",
	  "parentName":"ABC",
      "total":"Security ABC",
      "clientID":"8747238",
      "isin":"IR0004324843",
      "holdType":"MARKETS",
      "country":"SCOTLAND",
      "currency":"USD",
      "assetType":"EQUITIES",
      "ytm":"0.0",
      "oad":"0.0",
      "mv":"482839",
      "totalmv":"482839",
      "mvp":"12%",
      "description":"Security ABC"
   },
   {
      "block":"ADR - DEV MARKETS ABC USD",
      "benchmark":"benchmark 1",
	  "parentName":"ABC",
      "total":"Security XYZ",
      "clientID":"6573000",
      "isin":"EN0004396400",
      "holdType":"MARKETS",
      "country":"SCOTLAND",
      "currency":"USD",
      "assetType":"EQUITIES",
      "ytm":"0.0",
      "oad":"0.0",
      "mv":"482839",
      "totalmv":"482839",
      "mvp":"18%",
      "description":"Security XYZ"
   },

   {
      "block":"CURRENCIES AUS AUD",
      "benchmark":"benchmark 7",
	  "parentName":"AUSTRALIA",
      "total":"AU Dollar",
      "clientID":"0910D09",
      "isin":"",
      "holdType":"CURRENCIES",
      "country":"AUSTRALIA",
      "currency":"AUD",
      "assetType":"Cash Equivalents",
      "ytm":"0.0",
      "oad":"0.0",
      "mv":"47436",
      "totalmv":"47436",
      "mvp":"1%",
      "description":"AUS Dollar"
   },
   {
      "block":"CURRENCIES AUS AUD",
      "benchmark":"benchmark 7",
	  "parentName":"AUSTRALIA",
      "total":"AU Dollar",
      "clientID":"0910D09",
      "isin":"",
      "holdType":"CURRENCIES",
      "country":"AUSTRALIA",
      "currency":"AUD",
      "assetType":"Cash Equivalents",
      "ytm":"0.0",
      "oad":"0.0",
      "mv":"83294",
      "totalmv":"83294",
      "mvp":"2%",
      "description":"AUS Dollar"
   },
   {
      "block":"CURRENCIES AUS AUD",
      "benchmark":"benchmark 7",
	  "parentName":"UNITED KINGDOM",
      "total":"UNITED KINGDOM",
      "clientID":"",
      "isin":"",
      "holdType":"",
      "country":"",
      "currency":"GBP",
      "assetType":"",
      "ytm":"0.0",
      "oad":"0.0",
      "mv":"-7006889",
      "totalmv":"-7006889",
      "mvp":"-4%",
      "description":""
   },
   {
      "block":"CURRENCIES AUS AUD",
      "benchmark":"benchmark 7",
	  "parentName":"US",
      "total":"US",
      "clientID":"",
      "isin":"",
      "holdType":"",
      "country":"",
      "currency":"USD",
      "assetType":"",
      "ytm":"0.0",
      "oad":"0.0",
      "mv":"-7006889",
      "totalmv":"-7006889",
      "mvp":"-4%",
      "description":""
   }
];
